### PR TITLE
Add the policies for opensdhift version 4.13

### PR DESCRIPTION
**Pull request by bardielle**

### CODE REVIEW

**Review by vkareh — CHANGES_REQUESTED** [review]
This won't work. These policies change regularly enough that you would need to tag a new release every time. We provide an API endpoint in OCM to address this issue.

You need to use the correct service API for this: https://api.openshift.com/#/default/get_api_clusters_mgmt_v1_aws_inquiries_sts_policies

**Comment by bardielle** [comment]
@vkareh this is a module that uses AWS provider only, that means that it cannot call OCM,
If we would like to call OCM for each creation, we need to add a new data source (as part of terraform-provider-ocm) that  calls to OCM in order to get the policies and it will looks like:
```
data "ocm_policies" "account_role_policies" {
    rosa_openshift_version = var.rosa_openshift_version
}

module account_role{
  source = "terraform-redhat/rosa-sts/aws"
  version = "0.0.3"

  create_operator_roles = false
  create_oidc_provider = false
  create_account_roles = true

  account_role_prefix = var.account_role_prefix
  policies = data.ocm_policies.account_role_policies.policies 
  ocm_environment = var.ocm_env
  rosa_openshift_version=var.rosa_openshift_version
}

```
Also, it means several changes in the account roles creation which are not in the scope of the first release

**Comment by bardielle** [comment]
@vkareh let's talk about it today in our sync meeting.

**Comment by bardielle** [comment]
I opened a new PRs: 
 https://github.com/terraform-redhat/terraform-aws-rosa-sts/pull/6
 https://github.com/terraform-redhat/terraform-provider-ocm/pull/36
So closing that PR

**Pull request closed without merging**
